name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp keyfile ~/.ssh/id_rsa
        ssh -i keyfile -o StrictHostKeyChecking=no ubuntu@ec2-3-106-239-223.ap-southeast-2.compute.amazonaws.com "source ./deploy.sh"
